---
- name: libreoffice repository stat
  stat:
    path: "/etc/apt/sources.list.d/libreoffice.list"
  register: stat_result
- name: libreoffice repository remove
  file:
    path: "/etc/apt/sources.list.d/libreoffice.list"
    state: absent
  when: stat_result.stat.exists=True
- name: libreoffice repository add
  apt_repository:
    validate_certs: no
    repo: "ppa:libreoffice/ppa"
    state: present
    filename: libreoffice
- name: libreoffice repository amd64
  replace:
    path: "/etc/apt/sources.list.d/libreoffice.list"
    regexp: 'deb[ \t].*http'
    replace: 'deb [arch=amd64] http'
- name: libreoffice
  apt:
    name:
    - libreoffice
    state: latest
    update_cache: yes
