---
- name: network vpn connectors
  apt:
    name:
    - wireguard
    state: latest
- name: wireguard cli helpers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    owner: "{{ group }}"
  with_items:
    - { src: "bin/wgadd", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/wgdel", dest: "{{ home }}/bin/", mode: "0755" }
