---
# syncthing
- name: syncthing repo key
  apt_key:
    url: "https://syncthing.net/release-key.txt"
    state: present
- name: syncthing repository remove
  file:
    path: "/etc/apt/sources.list.d/syncthing.list"
    state: absent
- name: syncthing repository add
  apt_repository:
    validate_certs: no
    repo: "deb [arch=amd64] https://apt.syncthing.net/ syncthing stable"
    state: present
    filename: syncthing
    update_cache: yes
- name: syncthing
  apt:
    name:
    - syncthing
    state: latest
# nextcloud-client
- name: nextcloud desktop client repo remove
  file:
    path: "/etc/apt/sources.list.d/nextcloud-client.list"
    state: absent
- name: nextcloud desktop client repo add
  apt_repository:
    validate_certs: no
    repo: "ppa:nextcloud-devs/client"
    filename: nextcloud-client
    state: present
- name: nextcloud repo amd64
  replace:
    path: "/etc/apt/sources.list.d/nextcloud-client.list"
    regexp: 'deb[ \t].*http'
    replace: 'deb [arch=amd64] http'
- name: nextcloud desktop client
  apt:
    name:
      - nextcloud-client
    state: latest
    update_cache: yes
